language: php

php:
  - 5.6
  - 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml